# StackName:vpc

Resources:

  devVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: "10.1.0.0/17"
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
      InstanceTenancy: 'default'
      Tags:
      - Key: Name
        Value: dev-vpc

  stgVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: "10.1.128.0/17"
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
      InstanceTenancy: 'default'
      Tags:
      - Key: Name
        Value: stg-vpc

  prdVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: "10.2.0.0/16"
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
      InstanceTenancy: 'default'
      Tags:
      - Key: Name
        Value: prd-vpc
